/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgressPane.java
 *
 * Created on Nov 4, 2010, 11:32:19 AM
 */

package bayesserver;

import bayesserver.Constants.INSTALLATION;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JProgressBar;

/**
 *
 * @author apple
 */
public class ProgressPane extends javax.swing.JPanel {
    ImageIcon unSelectIcon     = new javax.swing.ImageIcon(getClass().getResource("/bayesserver/resources/buttons/rb.gif"));
    ImageIcon selectedIcon     = new javax.swing.ImageIcon(getClass().getResource("/bayesserver/resources/buttons/rbs.gif"));
    ImageIcon progressIcon     = new javax.swing.ImageIcon(getClass().getResource("/bayesserver/resources/buttons/rbrs.gif"));

    ImageIcon downloadIcon    =  new javax.swing.ImageIcon(getClass().getResource("/bayesserver/resources/icons/installation-progress.png"));
    ImageIcon unzipIcon    =  new javax.swing.ImageIcon(getClass().getResource("/bayesserver/resources/icons/unzip.png"));
    ImageIcon configureIcon    =  new javax.swing.ImageIcon(getClass().getResource("/bayesserver/resources/icons/configure.png"));


    public static final String START_INPROGRESS     = "Stating Installation";
    public static final String START_DONE           = "Installation Has Started";

    public static final String DOWNLOAD_INPROGRESS     = "Stating Installation";
    public static final String DOWNLOAD_DONE           = "Installation Has Started";


    /** Creates new form ProgressPane */
    public ProgressPane() {
        initComponents();
    }

    public void setIndeterminate(boolean isIndertm){
        progreeBar.setIndeterminate(isIndertm);
    }
    public void setNote(String str){
        noteLabel.setText(str);
    }
    public void setMessage(String str){
        messageLabel.setText(str);
    }
    public void updateInstallationStatus(INSTALLATION inst){
        switch(inst){
            case START :
                i1Icon.setIcon(progressIcon);
                i2Icon.setIcon(unSelectIcon);
                i3Icon.setIcon(unSelectIcon);
                i4Icon.setIcon(unSelectIcon);
                i5Icon.setIcon(unSelectIcon);
                iconLabel.setIcon(downloadIcon );
                break;

            case DOWNLOAD :
                i1Icon.setIcon(selectedIcon);
                i2Icon.setIcon(progressIcon);
                i3Icon.setIcon(unSelectIcon);
                i4Icon.setIcon(unSelectIcon);
                i5Icon.setIcon(unSelectIcon);
                iconLabel.setIcon(downloadIcon );
                break;

            case UNARCHIVE :
                i1Icon.setIcon(selectedIcon);
                i2Icon.setIcon(selectedIcon);
                i3Icon.setIcon(progressIcon);
                i4Icon.setIcon(unSelectIcon);
                i5Icon.setIcon(unSelectIcon);
                iconLabel.setIcon(unzipIcon  );
                break;

            case INSTALL :
                i1Icon.setIcon(selectedIcon);
                i2Icon.setIcon(selectedIcon);
                i3Icon.setIcon(selectedIcon);
                i4Icon.setIcon(selectedIcon);
                i5Icon.setIcon(progressIcon);
                iconLabel.setIcon(configureIcon  );
                break;

            case COMPLETE :
                i1Icon.setIcon(selectedIcon);
                i2Icon.setIcon(selectedIcon);
                i3Icon.setIcon(selectedIcon);
                i4Icon.setIcon(selectedIcon);
                i5Icon.setIcon(selectedIcon);
                iconLabel.setIcon(configureIcon  );
                break;

            default :
                i1Icon.setIcon(unSelectIcon);
                i2Icon.setIcon(unSelectIcon);
                i3Icon.setIcon(unSelectIcon);
                i4Icon.setIcon(unSelectIcon);
                i5Icon.setIcon(unSelectIcon);
                iconLabel.setIcon(downloadIcon );
                break;
        }

    }

    public JProgressBar getProgressBar(){
        return progreeBar;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        i2Icon = new javax.swing.JLabel();
        i1Icon = new javax.swing.JLabel();
        i3Icon = new javax.swing.JLabel();
        i4Icon = new javax.swing.JLabel();
        i5Icon = new javax.swing.JLabel();
        stagePane = new javax.swing.JPanel();
        progreeBar = new javax.swing.JProgressBar();
        noteLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Bayesian Server Sowatware Installation Progress");
        jLabel1.setName("jLabel1"); // NOI18N

        i2Icon.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        i2Icon.setIcon(unSelectIcon);
        i2Icon.setText("Installation Files Downloaded");
        i2Icon.setName("i2Icon"); // NOI18N

        i1Icon.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        i1Icon.setIcon(unSelectIcon);
        i1Icon.setText("Installation Started");
        i1Icon.setName("i1Icon"); // NOI18N

        i3Icon.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        i3Icon.setIcon(unSelectIcon);
        i3Icon.setText("Installation Files Unzipped");
        i3Icon.setName("i3Icon"); // NOI18N

        i4Icon.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        i4Icon.setIcon(unSelectIcon);
        i4Icon.setText("Configuration Completed");
        i4Icon.setName("i4Icon"); // NOI18N

        i5Icon.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        i5Icon.setIcon(unSelectIcon);
        i5Icon.setText("Installation Completed");
        i5Icon.setName("i5Icon"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(i2Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(i3Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(i4Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(i5Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(i1Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(289, 289, 289))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {i1Icon, i2Icon, i3Icon, i4Icon, i5Icon}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(i1Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(i2Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(i3Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(i4Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(i5Icon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        stagePane.setName("stagePane"); // NOI18N

        progreeBar.setIndeterminate(true);
        progreeBar.setName("progreeBar"); // NOI18N

        noteLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        noteLabel.setName("noteLabel"); // NOI18N

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bayesserver/resources/icons/installation-progress.png"))); // NOI18N
        iconLabel.setName("iconLabel"); // NOI18N

        messageLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        messageLabel.setName("messageLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout stagePaneLayout = new org.jdesktop.layout.GroupLayout(stagePane);
        stagePane.setLayout(stagePaneLayout);
        stagePaneLayout.setHorizontalGroup(
            stagePaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stagePaneLayout.createSequentialGroup()
                .addContainerGap()
                .add(stagePaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(stagePaneLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(iconLabel)
                        .add(18, 18, 18)
                        .add(messageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(stagePaneLayout.createSequentialGroup()
                        .add(progreeBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                        .add(26, 26, 26))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, stagePaneLayout.createSequentialGroup()
                        .add(noteLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        stagePaneLayout.setVerticalGroup(
            stagePaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stagePaneLayout.createSequentialGroup()
                .add(42, 42, 42)
                .add(stagePaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(iconLabel)
                    .add(messageLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 142, Short.MAX_VALUE)
                .add(noteLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(progreeBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(8, 8, 8))
        );

        add(stagePane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
 public static void createAndShowGUI() {

        //Create and set up the window.
        JFrame frame = new JFrame(" Bayes Analyze ");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
            }
        });
        frame.add(new ProgressPane ());

        //Display the window.
        frame.pack();
        frame.setVisible(true);
//        FidViewer.getInstance().updatePlot();
    }
    public static void main(String[] args) {
        //Schedule a job for the event-dispatching thread:
        //creating and showing this application's GUI.
     //   getSystemProperties();
       javax.swing.SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                createAndShowGUI();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel i1Icon;
    private javax.swing.JLabel i2Icon;
    private javax.swing.JLabel i3Icon;
    private javax.swing.JLabel i4Icon;
    private javax.swing.JLabel i5Icon;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JProgressBar progreeBar;
    private javax.swing.JPanel stagePane;
    // End of variables declaration//GEN-END:variables

}
